/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IdentitiesRouteImport } from './routes/identities'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AuthenticatedCreateTeamRouteImport } from './routes/_authenticated/create-team'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingCookiePolicyRouteImport } from './routes/_marketing/cookie-policy'
import { Route as MarketingFaqRouteImport } from './routes/_marketing/faq'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingPrivacyPolicyRouteImport } from './routes/_marketing/privacy-policy'
import { Route as MarketingTermsOfServiceRouteImport } from './routes/_marketing/terms-of-service'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteRouteImport } from './routes/admin/accounts/route'
import { Route as AdminCmsRouteRouteImport } from './routes/admin/cms/route'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as JoinAcceptRouteImport } from './routes/join/accept'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsBillingRouteRouteImport } from './routes/_authenticated/settings/billing/route'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing/blog/index'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing/blog/$slug'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as AdminAccountsIdRouteImport } from './routes/admin/accounts/$id'
import { Route as AdminCmsIndexRouteImport } from './routes/admin/cms/index'
import { Route as AdminCmsSettingsRouteRouteImport } from './routes/admin/cms/settings/route'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiCmsSplatRouteImport } from './routes/api/cms/$'
import { Route as ApiDbWebhookRouteImport } from './routes/api/db/webhook'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AuthCallbackErrorRouteImport } from './routes/auth/callback/error'
import { Route as AuthenticatedSettingsBillingIndexRouteImport } from './routes/_authenticated/settings/billing/index'
import { Route as AuthenticatedSettingsBillingReturnRouteImport } from './routes/_authenticated/settings/billing/return'
import { Route as AuthenticatedSettingsMembersPoliciesRouteImport } from './routes/_authenticated/settings/members/policies'
import { Route as AdminCmsAuditLogsIndexRouteImport } from './routes/admin/cms/audit-logs/index'
import { Route as AdminCmsAuditLogsIdRouteImport } from './routes/admin/cms/audit-logs/$id'
import { Route as AdminCmsDashboardsIndexRouteImport } from './routes/admin/cms/dashboards/index'
import { Route as AdminCmsResourcesIndexRouteImport } from './routes/admin/cms/resources/index'
import { Route as AdminCmsSettingsIndexRouteImport } from './routes/admin/cms/settings/index'
import { Route as AdminCmsSettingsAuthenticationRouteImport } from './routes/admin/cms/settings/authentication'
import { Route as AdminCmsSettingsGeneralRouteImport } from './routes/admin/cms/settings/general'
import { Route as AdminCmsStorageIndexRouteImport } from './routes/admin/cms/storage/index'
import { Route as AdminCmsStorageBucketRouteImport } from './routes/admin/cms/storage/$bucket'
import { Route as AdminCmsUsersIndexRouteImport } from './routes/admin/cms/users/index'
import { Route as AdminCmsUsersIdRouteImport } from './routes/admin/cms/users/$id'
import { Route as AdminCmsSettingsMembersIndexRouteImport } from './routes/admin/cms/settings/members/index'
import { Route as AdminCmsSettingsMembersIdRouteImport } from './routes/admin/cms/settings/members/$id'
import { Route as AdminCmsResourcesSchemaTableIndexRouteImport } from './routes/admin/cms/resources/$schema/$table/index'
import { Route as AdminCmsResourcesSchemaTableNewRouteImport } from './routes/admin/cms/resources/$schema/$table/new'
import { Route as AdminCmsResourcesSchemaTableRecordIndexRouteImport } from './routes/admin/cms/resources/$schema/$table/record/index'
import { Route as AdminCmsResourcesSchemaTableRecordEditRouteImport } from './routes/admin/cms/resources/$schema/$table/record/edit'
import { Route as AdminCmsResourcesSchemaTableRecordIdIndexRouteImport } from './routes/admin/cms/resources/$schema/$table/record/$id/index'
import { Route as AdminCmsResourcesSchemaTableRecordIdEditRouteImport } from './routes/admin/cms/resources/$schema/$table/record/$id/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesRoute = IdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateTeamRoute = AuthenticatedCreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingCookiePolicyRoute = MarketingCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRouteRoute = AdminAccountsRouteRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsRouteRoute = AdminCmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAcceptRoute = JoinAcceptRouteImport.update({
  id: '/join/accept',
  path: '/join/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRouteRoute =
  AuthenticatedSettingsBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAccountsRouteRoute,
} as any)
const AdminAccountsIdRoute = AdminAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAccountsRouteRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsSettingsRouteRoute = AdminCmsSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsSplatRoute = ApiCmsSplatRouteImport.update({
  id: '/api/cms/$',
  path: '/api/cms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbWebhookRoute = ApiDbWebhookRouteImport.update({
  id: '/api/db/webhook',
  path: '/api/db/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackErrorRoute = AuthCallbackErrorRouteImport.update({
  id: '/callback/error',
  path: '/callback/error',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsBillingIndexRoute =
  AuthenticatedSettingsBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsBillingRouteRoute,
  } as any)
const AuthenticatedSettingsBillingReturnRoute =
  AuthenticatedSettingsBillingReturnRouteImport.update({
    id: '/return',
    path: '/return',
    getParentRoute: () => AuthenticatedSettingsBillingRouteRoute,
  } as any)
const AuthenticatedSettingsMembersPoliciesRoute =
  AuthenticatedSettingsMembersPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedSettingsMembersRoute,
  } as any)
const AdminCmsAuditLogsIndexRoute = AdminCmsAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsAuditLogsIdRoute = AdminCmsAuditLogsIdRouteImport.update({
  id: '/audit-logs/$id',
  path: '/audit-logs/$id',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsDashboardsIndexRoute = AdminCmsDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsResourcesIndexRoute = AdminCmsResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsSettingsIndexRoute = AdminCmsSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsSettingsRouteRoute,
} as any)
const AdminCmsSettingsAuthenticationRoute =
  AdminCmsSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AdminCmsSettingsRouteRoute,
  } as any)
const AdminCmsSettingsGeneralRoute = AdminCmsSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminCmsSettingsRouteRoute,
} as any)
const AdminCmsStorageIndexRoute = AdminCmsStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsStorageBucketRoute = AdminCmsStorageBucketRouteImport.update({
  id: '/storage/$bucket',
  path: '/storage/$bucket',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsUsersIndexRoute = AdminCmsUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsUsersIdRoute = AdminCmsUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminCmsRouteRoute,
} as any)
const AdminCmsSettingsMembersIndexRoute =
  AdminCmsSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AdminCmsSettingsRouteRoute,
  } as any)
const AdminCmsSettingsMembersIdRoute =
  AdminCmsSettingsMembersIdRouteImport.update({
    id: '/members/$id',
    path: '/members/$id',
    getParentRoute: () => AdminCmsSettingsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableIndexRoute =
  AdminCmsResourcesSchemaTableIndexRouteImport.update({
    id: '/resources/$schema/$table/',
    path: '/resources/$schema/$table/',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableNewRoute =
  AdminCmsResourcesSchemaTableNewRouteImport.update({
    id: '/resources/$schema/$table/new',
    path: '/resources/$schema/$table/new',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableRecordIndexRoute =
  AdminCmsResourcesSchemaTableRecordIndexRouteImport.update({
    id: '/resources/$schema/$table/record/',
    path: '/resources/$schema/$table/record/',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableRecordEditRoute =
  AdminCmsResourcesSchemaTableRecordEditRouteImport.update({
    id: '/resources/$schema/$table/record/edit',
    path: '/resources/$schema/$table/record/edit',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableRecordIdIndexRoute =
  AdminCmsResourcesSchemaTableRecordIdIndexRouteImport.update({
    id: '/resources/$schema/$table/record/$id/',
    path: '/resources/$schema/$table/record/$id/',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)
const AdminCmsResourcesSchemaTableRecordIdEditRoute =
  AdminCmsResourcesSchemaTableRecordIdEditRouteImport.update({
    id: '/resources/$schema/$table/record/$id/edit',
    path: '/resources/$schema/$table/record/$id/edit',
    getParentRoute: () => AdminCmsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/identities': typeof IdentitiesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRouteRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteRouteWithChildren
  '/create-team': typeof AuthenticatedCreateTeamRoute
  '/contact': typeof MarketingContactRoute
  '/cookie-policy': typeof MarketingCookiePolicyRoute
  '/faq': typeof MarketingFaqRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/accept': typeof JoinAcceptRoute
  '/admin/': typeof AdminIndexRoute
  '/join/': typeof JoinIndexRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRouteRouteWithChildren
  '/admin/cms/settings': typeof AdminCmsSettingsRouteRouteWithChildren
  '/settings/members': typeof AuthenticatedSettingsMembersRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/api/db/webhook': typeof ApiDbWebhookRoute
  '/auth/callback/error': typeof AuthCallbackErrorRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/settings/billing/return': typeof AuthenticatedSettingsBillingReturnRoute
  '/settings/members/policies': typeof AuthenticatedSettingsMembersPoliciesRoute
  '/admin/cms/audit-logs/$id': typeof AdminCmsAuditLogsIdRoute
  '/admin/cms/settings/authentication': typeof AdminCmsSettingsAuthenticationRoute
  '/admin/cms/settings/general': typeof AdminCmsSettingsGeneralRoute
  '/admin/cms/storage/$bucket': typeof AdminCmsStorageBucketRoute
  '/admin/cms/users/$id': typeof AdminCmsUsersIdRoute
  '/settings/billing/': typeof AuthenticatedSettingsBillingIndexRoute
  '/admin/cms/audit-logs/': typeof AdminCmsAuditLogsIndexRoute
  '/admin/cms/dashboards/': typeof AdminCmsDashboardsIndexRoute
  '/admin/cms/resources/': typeof AdminCmsResourcesIndexRoute
  '/admin/cms/settings/': typeof AdminCmsSettingsIndexRoute
  '/admin/cms/storage/': typeof AdminCmsStorageIndexRoute
  '/admin/cms/users/': typeof AdminCmsUsersIndexRoute
  '/admin/cms/settings/members/$id': typeof AdminCmsSettingsMembersIdRoute
  '/admin/cms/settings/members/': typeof AdminCmsSettingsMembersIndexRoute
  '/admin/cms/resources/$schema/$table/new': typeof AdminCmsResourcesSchemaTableNewRoute
  '/admin/cms/resources/$schema/$table/': typeof AdminCmsResourcesSchemaTableIndexRoute
  '/admin/cms/resources/$schema/$table/record/edit': typeof AdminCmsResourcesSchemaTableRecordEditRoute
  '/admin/cms/resources/$schema/$table/record/': typeof AdminCmsResourcesSchemaTableRecordIndexRoute
  '/admin/cms/resources/$schema/$table/record/$id/edit': typeof AdminCmsResourcesSchemaTableRecordIdEditRoute
  '/admin/cms/resources/$schema/$table/record/$id/': typeof AdminCmsResourcesSchemaTableRecordIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/identities': typeof IdentitiesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/create-team': typeof AuthenticatedCreateTeamRoute
  '/contact': typeof MarketingContactRoute
  '/cookie-policy': typeof MarketingCookiePolicyRoute
  '/faq': typeof MarketingFaqRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/accept': typeof JoinAcceptRoute
  '/admin': typeof AdminIndexRoute
  '/join': typeof JoinIndexRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRouteWithChildren
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/api/db/webhook': typeof ApiDbWebhookRoute
  '/auth/callback/error': typeof AuthCallbackErrorRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/settings/billing/return': typeof AuthenticatedSettingsBillingReturnRoute
  '/settings/members/policies': typeof AuthenticatedSettingsMembersPoliciesRoute
  '/admin/cms/audit-logs/$id': typeof AdminCmsAuditLogsIdRoute
  '/admin/cms/settings/authentication': typeof AdminCmsSettingsAuthenticationRoute
  '/admin/cms/settings/general': typeof AdminCmsSettingsGeneralRoute
  '/admin/cms/storage/$bucket': typeof AdminCmsStorageBucketRoute
  '/admin/cms/users/$id': typeof AdminCmsUsersIdRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingIndexRoute
  '/admin/cms/audit-logs': typeof AdminCmsAuditLogsIndexRoute
  '/admin/cms/dashboards': typeof AdminCmsDashboardsIndexRoute
  '/admin/cms/resources': typeof AdminCmsResourcesIndexRoute
  '/admin/cms/settings': typeof AdminCmsSettingsIndexRoute
  '/admin/cms/storage': typeof AdminCmsStorageIndexRoute
  '/admin/cms/users': typeof AdminCmsUsersIndexRoute
  '/admin/cms/settings/members/$id': typeof AdminCmsSettingsMembersIdRoute
  '/admin/cms/settings/members': typeof AdminCmsSettingsMembersIndexRoute
  '/admin/cms/resources/$schema/$table/new': typeof AdminCmsResourcesSchemaTableNewRoute
  '/admin/cms/resources/$schema/$table': typeof AdminCmsResourcesSchemaTableIndexRoute
  '/admin/cms/resources/$schema/$table/record/edit': typeof AdminCmsResourcesSchemaTableRecordEditRoute
  '/admin/cms/resources/$schema/$table/record': typeof AdminCmsResourcesSchemaTableRecordIndexRoute
  '/admin/cms/resources/$schema/$table/record/$id/edit': typeof AdminCmsResourcesSchemaTableRecordIdEditRoute
  '/admin/cms/resources/$schema/$table/record/$id': typeof AdminCmsResourcesSchemaTableRecordIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/identities': typeof IdentitiesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRouteRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteRouteWithChildren
  '/_authenticated/create-team': typeof AuthenticatedCreateTeamRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/cookie-policy': typeof MarketingCookiePolicyRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/version': typeof ApiVersionRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/join/accept': typeof JoinAcceptRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/join/': typeof JoinIndexRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRouteRouteWithChildren
  '/admin/cms/settings': typeof AdminCmsSettingsRouteRouteWithChildren
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRouteWithChildren
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/cms/$': typeof ApiCmsSplatRoute
  '/api/db/webhook': typeof ApiDbWebhookRoute
  '/auth/callback/error': typeof AuthCallbackErrorRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/_authenticated/settings/billing/return': typeof AuthenticatedSettingsBillingReturnRoute
  '/_authenticated/settings/members/policies': typeof AuthenticatedSettingsMembersPoliciesRoute
  '/admin/cms/audit-logs/$id': typeof AdminCmsAuditLogsIdRoute
  '/admin/cms/settings/authentication': typeof AdminCmsSettingsAuthenticationRoute
  '/admin/cms/settings/general': typeof AdminCmsSettingsGeneralRoute
  '/admin/cms/storage/$bucket': typeof AdminCmsStorageBucketRoute
  '/admin/cms/users/$id': typeof AdminCmsUsersIdRoute
  '/_authenticated/settings/billing/': typeof AuthenticatedSettingsBillingIndexRoute
  '/admin/cms/audit-logs/': typeof AdminCmsAuditLogsIndexRoute
  '/admin/cms/dashboards/': typeof AdminCmsDashboardsIndexRoute
  '/admin/cms/resources/': typeof AdminCmsResourcesIndexRoute
  '/admin/cms/settings/': typeof AdminCmsSettingsIndexRoute
  '/admin/cms/storage/': typeof AdminCmsStorageIndexRoute
  '/admin/cms/users/': typeof AdminCmsUsersIndexRoute
  '/admin/cms/settings/members/$id': typeof AdminCmsSettingsMembersIdRoute
  '/admin/cms/settings/members/': typeof AdminCmsSettingsMembersIndexRoute
  '/admin/cms/resources/$schema/$table/new': typeof AdminCmsResourcesSchemaTableNewRoute
  '/admin/cms/resources/$schema/$table/': typeof AdminCmsResourcesSchemaTableIndexRoute
  '/admin/cms/resources/$schema/$table/record/edit': typeof AdminCmsResourcesSchemaTableRecordEditRoute
  '/admin/cms/resources/$schema/$table/record/': typeof AdminCmsResourcesSchemaTableRecordIndexRoute
  '/admin/cms/resources/$schema/$table/record/$id/edit': typeof AdminCmsResourcesSchemaTableRecordIdEditRoute
  '/admin/cms/resources/$schema/$table/record/$id/': typeof AdminCmsResourcesSchemaTableRecordIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/identities'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/update-password'
    | '/dashboard'
    | '/settings'
    | '/admin/accounts'
    | '/admin/cms'
    | '/create-team'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/healthcheck'
    | '/api/version'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/accept'
    | '/admin/'
    | '/join/'
    | '/settings/billing'
    | '/admin/cms/settings'
    | '/settings/members'
    | '/settings/profile'
    | '/blog/$slug'
    | '/admin/accounts/$id'
    | '/api/billing/webhook'
    | '/api/cms/$'
    | '/api/db/webhook'
    | '/auth/callback/error'
    | '/dashboard/'
    | '/settings/'
    | '/blog/'
    | '/admin/accounts/'
    | '/admin/cms/'
    | '/auth/callback/'
    | '/settings/billing/return'
    | '/settings/members/policies'
    | '/admin/cms/audit-logs/$id'
    | '/admin/cms/settings/authentication'
    | '/admin/cms/settings/general'
    | '/admin/cms/storage/$bucket'
    | '/admin/cms/users/$id'
    | '/settings/billing/'
    | '/admin/cms/audit-logs/'
    | '/admin/cms/dashboards/'
    | '/admin/cms/resources/'
    | '/admin/cms/settings/'
    | '/admin/cms/storage/'
    | '/admin/cms/users/'
    | '/admin/cms/settings/members/$id'
    | '/admin/cms/settings/members/'
    | '/admin/cms/resources/$schema/$table/new'
    | '/admin/cms/resources/$schema/$table/'
    | '/admin/cms/resources/$schema/$table/record/edit'
    | '/admin/cms/resources/$schema/$table/record/'
    | '/admin/cms/resources/$schema/$table/record/$id/edit'
    | '/admin/cms/resources/$schema/$table/record/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/identities'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/update-password'
    | '/create-team'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/healthcheck'
    | '/api/version'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/accept'
    | '/admin'
    | '/join'
    | '/settings/members'
    | '/settings/profile'
    | '/blog/$slug'
    | '/admin/accounts/$id'
    | '/api/billing/webhook'
    | '/api/cms/$'
    | '/api/db/webhook'
    | '/auth/callback/error'
    | '/dashboard'
    | '/settings'
    | '/blog'
    | '/admin/accounts'
    | '/admin/cms'
    | '/auth/callback'
    | '/settings/billing/return'
    | '/settings/members/policies'
    | '/admin/cms/audit-logs/$id'
    | '/admin/cms/settings/authentication'
    | '/admin/cms/settings/general'
    | '/admin/cms/storage/$bucket'
    | '/admin/cms/users/$id'
    | '/settings/billing'
    | '/admin/cms/audit-logs'
    | '/admin/cms/dashboards'
    | '/admin/cms/resources'
    | '/admin/cms/settings'
    | '/admin/cms/storage'
    | '/admin/cms/users'
    | '/admin/cms/settings/members/$id'
    | '/admin/cms/settings/members'
    | '/admin/cms/resources/$schema/$table/new'
    | '/admin/cms/resources/$schema/$table'
    | '/admin/cms/resources/$schema/$table/record/edit'
    | '/admin/cms/resources/$schema/$table/record'
    | '/admin/cms/resources/$schema/$table/record/$id/edit'
    | '/admin/cms/resources/$schema/$table/record/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_marketing'
    | '/admin'
    | '/auth'
    | '/identities'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/update-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/admin/accounts'
    | '/admin/cms'
    | '/_authenticated/create-team'
    | '/_marketing/contact'
    | '/_marketing/cookie-policy'
    | '/_marketing/faq'
    | '/_marketing/pricing'
    | '/_marketing/privacy-policy'
    | '/_marketing/terms-of-service'
    | '/api/healthcheck'
    | '/api/version'
    | '/auth/confirm'
    | '/auth/password-reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/join/accept'
    | '/_marketing/'
    | '/admin/'
    | '/join/'
    | '/_authenticated/settings/billing'
    | '/admin/cms/settings'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/profile'
    | '/_marketing/blog/$slug'
    | '/admin/accounts/$id'
    | '/api/billing/webhook'
    | '/api/cms/$'
    | '/api/db/webhook'
    | '/auth/callback/error'
    | '/_authenticated/dashboard/'
    | '/_authenticated/settings/'
    | '/_marketing/blog/'
    | '/admin/accounts/'
    | '/admin/cms/'
    | '/auth/callback/'
    | '/_authenticated/settings/billing/return'
    | '/_authenticated/settings/members/policies'
    | '/admin/cms/audit-logs/$id'
    | '/admin/cms/settings/authentication'
    | '/admin/cms/settings/general'
    | '/admin/cms/storage/$bucket'
    | '/admin/cms/users/$id'
    | '/_authenticated/settings/billing/'
    | '/admin/cms/audit-logs/'
    | '/admin/cms/dashboards/'
    | '/admin/cms/resources/'
    | '/admin/cms/settings/'
    | '/admin/cms/storage/'
    | '/admin/cms/users/'
    | '/admin/cms/settings/members/$id'
    | '/admin/cms/settings/members/'
    | '/admin/cms/resources/$schema/$table/new'
    | '/admin/cms/resources/$schema/$table/'
    | '/admin/cms/resources/$schema/$table/record/edit'
    | '/admin/cms/resources/$schema/$table/record/'
    | '/admin/cms/resources/$schema/$table/record/$id/edit'
    | '/admin/cms/resources/$schema/$table/record/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  IdentitiesRoute: typeof IdentitiesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiVersionRoute: typeof ApiVersionRoute
  JoinAcceptRoute: typeof JoinAcceptRoute
  JoinIndexRoute: typeof JoinIndexRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiCmsSplatRoute: typeof ApiCmsSplatRoute
  ApiDbWebhookRoute: typeof ApiDbWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities': {
      id: '/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-team': {
      id: '/_authenticated/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof AuthenticatedCreateTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/cookie-policy': {
      id: '/_marketing/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof MarketingCookiePolicyRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/accept': {
      id: '/join/accept'
      path: '/join/accept'
      fullPath: '/join/accept'
      preLoaderRoute: typeof JoinAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof AdminAccountsRouteRoute
    }
    '/admin/accounts/$id': {
      id: '/admin/accounts/$id'
      path: '/$id'
      fullPath: '/admin/accounts/$id'
      preLoaderRoute: typeof AdminAccountsIdRouteImport
      parentRoute: typeof AdminAccountsRouteRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/settings': {
      id: '/admin/cms/settings'
      path: '/settings'
      fullPath: '/admin/cms/settings'
      preLoaderRoute: typeof AdminCmsSettingsRouteRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/$': {
      id: '/api/cms/$'
      path: '/api/cms/$'
      fullPath: '/api/cms/$'
      preLoaderRoute: typeof ApiCmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/webhook': {
      id: '/api/db/webhook'
      path: '/api/db/webhook'
      fullPath: '/api/db/webhook'
      preLoaderRoute: typeof ApiDbWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/callback/error': {
      id: '/auth/callback/error'
      path: '/callback/error'
      fullPath: '/auth/callback/error'
      preLoaderRoute: typeof AuthCallbackErrorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/settings/billing/': {
      id: '/_authenticated/settings/billing/'
      path: '/'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof AuthenticatedSettingsBillingIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsBillingRouteRoute
    }
    '/_authenticated/settings/billing/return': {
      id: '/_authenticated/settings/billing/return'
      path: '/return'
      fullPath: '/settings/billing/return'
      preLoaderRoute: typeof AuthenticatedSettingsBillingReturnRouteImport
      parentRoute: typeof AuthenticatedSettingsBillingRouteRoute
    }
    '/_authenticated/settings/members/policies': {
      id: '/_authenticated/settings/members/policies'
      path: '/policies'
      fullPath: '/settings/members/policies'
      preLoaderRoute: typeof AuthenticatedSettingsMembersPoliciesRouteImport
      parentRoute: typeof AuthenticatedSettingsMembersRoute
    }
    '/admin/cms/audit-logs/': {
      id: '/admin/cms/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/cms/audit-logs/'
      preLoaderRoute: typeof AdminCmsAuditLogsIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/audit-logs/$id': {
      id: '/admin/cms/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/admin/cms/audit-logs/$id'
      preLoaderRoute: typeof AdminCmsAuditLogsIdRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/dashboards/': {
      id: '/admin/cms/dashboards/'
      path: '/dashboards'
      fullPath: '/admin/cms/dashboards/'
      preLoaderRoute: typeof AdminCmsDashboardsIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/': {
      id: '/admin/cms/resources/'
      path: '/resources'
      fullPath: '/admin/cms/resources/'
      preLoaderRoute: typeof AdminCmsResourcesIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/settings/': {
      id: '/admin/cms/settings/'
      path: '/'
      fullPath: '/admin/cms/settings/'
      preLoaderRoute: typeof AdminCmsSettingsIndexRouteImport
      parentRoute: typeof AdminCmsSettingsRouteRoute
    }
    '/admin/cms/settings/authentication': {
      id: '/admin/cms/settings/authentication'
      path: '/authentication'
      fullPath: '/admin/cms/settings/authentication'
      preLoaderRoute: typeof AdminCmsSettingsAuthenticationRouteImport
      parentRoute: typeof AdminCmsSettingsRouteRoute
    }
    '/admin/cms/settings/general': {
      id: '/admin/cms/settings/general'
      path: '/general'
      fullPath: '/admin/cms/settings/general'
      preLoaderRoute: typeof AdminCmsSettingsGeneralRouteImport
      parentRoute: typeof AdminCmsSettingsRouteRoute
    }
    '/admin/cms/storage/': {
      id: '/admin/cms/storage/'
      path: '/storage'
      fullPath: '/admin/cms/storage/'
      preLoaderRoute: typeof AdminCmsStorageIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/storage/$bucket': {
      id: '/admin/cms/storage/$bucket'
      path: '/storage/$bucket'
      fullPath: '/admin/cms/storage/$bucket'
      preLoaderRoute: typeof AdminCmsStorageBucketRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/users/': {
      id: '/admin/cms/users/'
      path: '/users'
      fullPath: '/admin/cms/users/'
      preLoaderRoute: typeof AdminCmsUsersIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/users/$id': {
      id: '/admin/cms/users/$id'
      path: '/users/$id'
      fullPath: '/admin/cms/users/$id'
      preLoaderRoute: typeof AdminCmsUsersIdRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/settings/members/': {
      id: '/admin/cms/settings/members/'
      path: '/members'
      fullPath: '/admin/cms/settings/members/'
      preLoaderRoute: typeof AdminCmsSettingsMembersIndexRouteImport
      parentRoute: typeof AdminCmsSettingsRouteRoute
    }
    '/admin/cms/settings/members/$id': {
      id: '/admin/cms/settings/members/$id'
      path: '/members/$id'
      fullPath: '/admin/cms/settings/members/$id'
      preLoaderRoute: typeof AdminCmsSettingsMembersIdRouteImport
      parentRoute: typeof AdminCmsSettingsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/': {
      id: '/admin/cms/resources/$schema/$table/'
      path: '/resources/$schema/$table'
      fullPath: '/admin/cms/resources/$schema/$table/'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/new': {
      id: '/admin/cms/resources/$schema/$table/new'
      path: '/resources/$schema/$table/new'
      fullPath: '/admin/cms/resources/$schema/$table/new'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableNewRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/record/': {
      id: '/admin/cms/resources/$schema/$table/record/'
      path: '/resources/$schema/$table/record'
      fullPath: '/admin/cms/resources/$schema/$table/record/'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableRecordIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/record/edit': {
      id: '/admin/cms/resources/$schema/$table/record/edit'
      path: '/resources/$schema/$table/record/edit'
      fullPath: '/admin/cms/resources/$schema/$table/record/edit'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableRecordEditRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/record/$id/': {
      id: '/admin/cms/resources/$schema/$table/record/$id/'
      path: '/resources/$schema/$table/record/$id'
      fullPath: '/admin/cms/resources/$schema/$table/record/$id/'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableRecordIdIndexRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
    '/admin/cms/resources/$schema/$table/record/$id/edit': {
      id: '/admin/cms/resources/$schema/$table/record/$id/edit'
      path: '/resources/$schema/$table/record/$id/edit'
      fullPath: '/admin/cms/resources/$schema/$table/record/$id/edit'
      preLoaderRoute: typeof AdminCmsResourcesSchemaTableRecordIdEditRouteImport
      parentRoute: typeof AdminCmsRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedSettingsBillingRouteRouteChildren {
  AuthenticatedSettingsBillingReturnRoute: typeof AuthenticatedSettingsBillingReturnRoute
  AuthenticatedSettingsBillingIndexRoute: typeof AuthenticatedSettingsBillingIndexRoute
}

const AuthenticatedSettingsBillingRouteRouteChildren: AuthenticatedSettingsBillingRouteRouteChildren =
  {
    AuthenticatedSettingsBillingReturnRoute:
      AuthenticatedSettingsBillingReturnRoute,
    AuthenticatedSettingsBillingIndexRoute:
      AuthenticatedSettingsBillingIndexRoute,
  }

const AuthenticatedSettingsBillingRouteRouteWithChildren =
  AuthenticatedSettingsBillingRouteRoute._addFileChildren(
    AuthenticatedSettingsBillingRouteRouteChildren,
  )

interface AuthenticatedSettingsMembersRouteChildren {
  AuthenticatedSettingsMembersPoliciesRoute: typeof AuthenticatedSettingsMembersPoliciesRoute
}

const AuthenticatedSettingsMembersRouteChildren: AuthenticatedSettingsMembersRouteChildren =
  {
    AuthenticatedSettingsMembersPoliciesRoute:
      AuthenticatedSettingsMembersPoliciesRoute,
  }

const AuthenticatedSettingsMembersRouteWithChildren =
  AuthenticatedSettingsMembersRoute._addFileChildren(
    AuthenticatedSettingsMembersRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsBillingRouteRoute: typeof AuthenticatedSettingsBillingRouteRouteWithChildren
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRouteWithChildren
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsBillingRouteRoute:
      AuthenticatedSettingsBillingRouteRouteWithChildren,
    AuthenticatedSettingsMembersRoute:
      AuthenticatedSettingsMembersRouteWithChildren,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedCreateTeamRoute: typeof AuthenticatedCreateTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedCreateTeamRoute: AuthenticatedCreateTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketingRouteRouteChildren {
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingCookiePolicyRoute: typeof MarketingCookiePolicyRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingContactRoute: MarketingContactRoute,
  MarketingCookiePolicyRoute: MarketingCookiePolicyRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface AdminAccountsRouteRouteChildren {
  AdminAccountsIdRoute: typeof AdminAccountsIdRoute
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
}

const AdminAccountsRouteRouteChildren: AdminAccountsRouteRouteChildren = {
  AdminAccountsIdRoute: AdminAccountsIdRoute,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
}

const AdminAccountsRouteRouteWithChildren =
  AdminAccountsRouteRoute._addFileChildren(AdminAccountsRouteRouteChildren)

interface AdminCmsSettingsRouteRouteChildren {
  AdminCmsSettingsAuthenticationRoute: typeof AdminCmsSettingsAuthenticationRoute
  AdminCmsSettingsGeneralRoute: typeof AdminCmsSettingsGeneralRoute
  AdminCmsSettingsIndexRoute: typeof AdminCmsSettingsIndexRoute
  AdminCmsSettingsMembersIdRoute: typeof AdminCmsSettingsMembersIdRoute
  AdminCmsSettingsMembersIndexRoute: typeof AdminCmsSettingsMembersIndexRoute
}

const AdminCmsSettingsRouteRouteChildren: AdminCmsSettingsRouteRouteChildren = {
  AdminCmsSettingsAuthenticationRoute: AdminCmsSettingsAuthenticationRoute,
  AdminCmsSettingsGeneralRoute: AdminCmsSettingsGeneralRoute,
  AdminCmsSettingsIndexRoute: AdminCmsSettingsIndexRoute,
  AdminCmsSettingsMembersIdRoute: AdminCmsSettingsMembersIdRoute,
  AdminCmsSettingsMembersIndexRoute: AdminCmsSettingsMembersIndexRoute,
}

const AdminCmsSettingsRouteRouteWithChildren =
  AdminCmsSettingsRouteRoute._addFileChildren(
    AdminCmsSettingsRouteRouteChildren,
  )

interface AdminCmsRouteRouteChildren {
  AdminCmsSettingsRouteRoute: typeof AdminCmsSettingsRouteRouteWithChildren
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
  AdminCmsAuditLogsIdRoute: typeof AdminCmsAuditLogsIdRoute
  AdminCmsStorageBucketRoute: typeof AdminCmsStorageBucketRoute
  AdminCmsUsersIdRoute: typeof AdminCmsUsersIdRoute
  AdminCmsAuditLogsIndexRoute: typeof AdminCmsAuditLogsIndexRoute
  AdminCmsDashboardsIndexRoute: typeof AdminCmsDashboardsIndexRoute
  AdminCmsResourcesIndexRoute: typeof AdminCmsResourcesIndexRoute
  AdminCmsStorageIndexRoute: typeof AdminCmsStorageIndexRoute
  AdminCmsUsersIndexRoute: typeof AdminCmsUsersIndexRoute
  AdminCmsResourcesSchemaTableNewRoute: typeof AdminCmsResourcesSchemaTableNewRoute
  AdminCmsResourcesSchemaTableIndexRoute: typeof AdminCmsResourcesSchemaTableIndexRoute
  AdminCmsResourcesSchemaTableRecordEditRoute: typeof AdminCmsResourcesSchemaTableRecordEditRoute
  AdminCmsResourcesSchemaTableRecordIndexRoute: typeof AdminCmsResourcesSchemaTableRecordIndexRoute
  AdminCmsResourcesSchemaTableRecordIdEditRoute: typeof AdminCmsResourcesSchemaTableRecordIdEditRoute
  AdminCmsResourcesSchemaTableRecordIdIndexRoute: typeof AdminCmsResourcesSchemaTableRecordIdIndexRoute
}

const AdminCmsRouteRouteChildren: AdminCmsRouteRouteChildren = {
  AdminCmsSettingsRouteRoute: AdminCmsSettingsRouteRouteWithChildren,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
  AdminCmsAuditLogsIdRoute: AdminCmsAuditLogsIdRoute,
  AdminCmsStorageBucketRoute: AdminCmsStorageBucketRoute,
  AdminCmsUsersIdRoute: AdminCmsUsersIdRoute,
  AdminCmsAuditLogsIndexRoute: AdminCmsAuditLogsIndexRoute,
  AdminCmsDashboardsIndexRoute: AdminCmsDashboardsIndexRoute,
  AdminCmsResourcesIndexRoute: AdminCmsResourcesIndexRoute,
  AdminCmsStorageIndexRoute: AdminCmsStorageIndexRoute,
  AdminCmsUsersIndexRoute: AdminCmsUsersIndexRoute,
  AdminCmsResourcesSchemaTableNewRoute: AdminCmsResourcesSchemaTableNewRoute,
  AdminCmsResourcesSchemaTableIndexRoute:
    AdminCmsResourcesSchemaTableIndexRoute,
  AdminCmsResourcesSchemaTableRecordEditRoute:
    AdminCmsResourcesSchemaTableRecordEditRoute,
  AdminCmsResourcesSchemaTableRecordIndexRoute:
    AdminCmsResourcesSchemaTableRecordIndexRoute,
  AdminCmsResourcesSchemaTableRecordIdEditRoute:
    AdminCmsResourcesSchemaTableRecordIdEditRoute,
  AdminCmsResourcesSchemaTableRecordIdIndexRoute:
    AdminCmsResourcesSchemaTableRecordIdIndexRoute,
}

const AdminCmsRouteRouteWithChildren = AdminCmsRouteRoute._addFileChildren(
  AdminCmsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAccountsRouteRoute: typeof AdminAccountsRouteRouteWithChildren
  AdminCmsRouteRoute: typeof AdminCmsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRouteRoute: AdminAccountsRouteRouteWithChildren,
  AdminCmsRouteRoute: AdminCmsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthCallbackErrorRoute: typeof AuthCallbackErrorRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthCallbackErrorRoute: AuthCallbackErrorRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  IdentitiesRoute: IdentitiesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiVersionRoute: ApiVersionRoute,
  JoinAcceptRoute: JoinAcceptRoute,
  JoinIndexRoute: JoinIndexRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiCmsSplatRoute: ApiCmsSplatRoute,
  ApiDbWebhookRoute: ApiDbWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
